### ISSUE TITLE
Control position of presentation window

### ISSUE THREAD

**Issue by mgkuhn** [pdfpc/pdfpc#627] opened 2021-11-20 18:15 UTC
It would be useful if option `-Z`/`--size` allowed not only the specification of the pixel dimensions of the window in `width:height` format, but also allowed to specify the position of the window on the screen.

Many older X11 application had a standard option `-geometry WIDTHxHEIGHT+XOFF+YOFF` for this, described in [`man 7 X`](https://www.x.org/releases/current/doc/man/man7/X.7.xhtml#heading7), which works like this:
>xterm -fn 6x10 -geometry 80x24+30+200 &
>xclock -geometry 48x48-0+0 &
>xload -geometry 48x48-96+0 &
>xbiff -geometry 48x48-48+0 &

Could something like the `-geometry` syntax also be provided for pdfpc, ideally not just for the presentation window, but also for the presenter window (see also #507)?

The parser for this syntax is already readily available in Xlib, in form of the [`XParseGeometry`](https://linux.die.net/man/3/xparsegeometry) function, and the entire algorithm for deciding where the window goes and how large it shall be is available in `XWMGeometry`.

**Comment by mgkuhn** [comment] 2021-11-20 18:33
See also the section [Parsing the Window Geometry](https://www.x.org/releases/current/doc/libX11/libX11/libX11.html#Parsing_the_Window_Geometry) in the *Xlib – C Language X Interface* manual.

**Comment by fnevgeny** [comment] 2021-12-08 12:53
Essentially, duplicate of #507. As to `XParseGeometry`, Vala is not X11-specific.

**Closed by fnevgeny** 2021-12-08 12:53 UTC
