### ISSUE TITLE
Bad window placement when using Wayland (GNOME 3.22)

### ISSUE THREAD

**Issue by svenpilz** [pdfpc/pdfpc#178] opened 2016-10-14 01:01 UTC
On GNOME 3.22 the window placement seems to be broken when a (now default) Wayland session is used. The window on the presenters view is shifted downwards so the background becomes visible, meaning timer and page number move outside the screen. It seems that the GNOME Shell “top bar” is replaced by the background wallpaper and the windows begins beneath it. But more importantly, the second screen just shows the background wallpaper.

X sessions work fine. GTK issue?

**Comment by diraimondo** [comment] 2016-10-20 08:19
I can confirm this on Wayland using Gnome 3.20. With an HIDpi main Screen is even worse.

**Comment by AndreasBilke** [comment] 2016-10-20 08:41
Any help in debugging/fixing is welcome!

**Comment by abaahy** [comment] 2016-11-07 20:47
LibreOffice Impress had the same problem in Fedora 25. It might help: https://bugzilla.redhat.com/show_bug.cgi?id=1390607

**Comment by qfvldaa2xn** [comment] 2016-12-22 13:11
I also have the same problem in the Evince presentation mode and i don't seem to be the only one:
https://bugzilla.gnome.org/show_bug.cgi?id=772930

Seems to be a GTK issue?

**Comment by qfvldaa2xn** [comment] 2017-01-03 08:26
Updating gdk-pixbuf2 to version 2.36.2 seems to resolved the issue.

**Comment by AndreasBilke** [comment] 2017-01-03 09:52
Can someone confirm this?

**Comment by Lygonius** [comment] 2017-01-04 12:34
I can't confirm. gdk version is "gdk-pixbuf2-2.36.2-1.fc25.x86_64" and the clock placement is still offscreen. But it seems that the "top bat" Problem only appears in the source compiled version. I checked the dnf version and the top allignment seems fine. Only the timer and pagenumber stays offscreen.

**Comment by diraimondo** [comment] 2017-01-04 18:36
On my Arch Linux the package `gdk-pixbuf2` just updated to 2.36.2 but I can't see any improvement on the multi-monitor problem under wayland. I also tried to build from source the 4.0.5 release of PDFPC. 

note: I can't see any change on evince that suffer of a similar problem.

**Comment by qfvldaa2xn** [comment] 2017-01-09 07:50
I have to appoligize, it was not the update that made it working.
But my laptop is normally starting with wayland, but now I realized it sometimes randomly starting with x11 (couldn't figure out yet why though...).

`GDK_BACKEND=x11 pdfpc -S pdfpc-demo.pdf` works for me.
But `GDK_BACKEND=wayland pdfpc -S pdfpc-demo.pdf` doesn't.

See:
![screenshot from 2017-01-08 22-20-14](https://cloud.githubusercontent.com/assets/13978911/21759935/8897bd8e-d648-11e6-8b3b-2194f8f6b83c.png)
Works fine.

![screenshot from 2017-01-09 08-38-45](https://cloud.githubusercontent.com/assets/13978911/21759936/889b4396-d648-11e6-9a6b-275939061975.png)
Just see the upper left quarter of the slide.

**Comment by AndreasBilke** [comment] 2017-01-19 20:48
I opened a PR #203 . Can everybody please give a feedback?

**Comment by AndreasBilke** [comment] 2017-01-31 10:35
@svenpilz Could you have a look at #204 to see if your problem is fixed?

**Comment by AndreasBilke** [comment] 2017-02-11 13:23
Please reopen the issue if your problem was not fixed with the latest master.

**Closed by AndreasBilke** 2017-02-11 13:23 UTC
