### ISSUE TITLE
Cut off of preview.

### ISSUE THREAD

**Issue by vrossum** [pdfpc/pdfpc#116] opened 2016-01-14 11:31 UTC
Hi
Great tool.
I find that the preview of the next slide on the console is cut off on the right when the two displays have a different aspect ratio.
For instance: external monitor 1280x800, laptop 1024x768.
(version 4.0.1)

**Comment by AndreasBilke** [comment] 2016-01-30 14:58
Could you test against the current master if your problem is fixed?

**Comment by vrossum** [comment] 2016-01-31 20:07
Hi

I think the problem occurs actually with any 1025x768 screen.

(with the latest version)
PS would be nice if pdfpc -v would say it is the git version.

On 30/01/16 14:58, Andreas Bilke wrote:
> Could you test against the current master if your problem is fixed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pdfpc/pdfpc/issues/116#issuecomment-177199990>.
>

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by andybarry** [comment] 2016-02-01 05:40
I can reproduce this with 1024x768 resolution.

**Comment by andybarry** [comment] 2016-02-01 19:09
This can be fixed if we reduce the font size in ````.bottomText````  So if we can figure out how to do that automatically, that should solve the problem.  In the meantime, @vrossum you can solve this by editing ````pdfpc.css```` to decrease the bottom text size or by creating one as the man page describes.

AKA:
````
.bottomText {
    font-size: 2em;
}
````

**Comment by AndreasBilke** [comment] 2016-02-11 10:02
@vrossum is your issue fixed with the latest master?

**Comment by AndreasBilke** [comment] 2016-08-02 08:19
Closed, because the submitter does not respond.

**Closed by AndreasBilke** 2016-08-02 08:19 UTC
