### ISSUE TITLE
Some movie files make pdfpc crash

### ISSUE THREAD

**Issue by ziotom78** [pdfpc/pdfpc#90] opened 2015-11-01 22:56 UTC
A presentation for my next class keeps making `pdfpc` crashing when displaying slides where _certain_ movies are to be played. The presentation is available here, as well as the animations it uses: https://dl.dropboxusercontent.com/u/27308314/pdfpc_movie_bug.tar.

The problem can be seen with slides 8, 16, and 18. No problems arise with slides 5, 24, 32, 33. This puzzles me, as it seems that the crash is not issued by the file format, nor by the video length.

I did a few debug checks, and it seems that the crash is issued by the call to `get_state` (https://github.com/pdfpc/pdfpc/blob/master/src/classes/action/movie.vala#L113). I am however not sure what is causing it, the syntax of the call seems to be perfectly legit.

**Comment by AndreasBilke** [comment] 2015-11-02 08:29
Two things:
- I have seen this problem before in my own presentations. But I never figured out if it is a pdfpc problem, a gstreamer problem or what ever
- In you example, for me, it never crashes. Every video works, except on slide 5. There I get the audio output but no video

I use arch linux where gstreamer and so on is up to date. Maybe this was a gstreamer problem and it is fixed now? I don't know, I will test your presentation on some other pc.

**Comment by ziotom78** [comment] 2015-11-02 09:43
Hi Andreas,

  Thank you for your answer. For the record, here is the error message:

`````
** (pdfpc:6478): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Screensaver inhibited
*** Error in `/home/tomasi/Projects/pdfpc/build/bin/pdfpc': free(): invalid pointer: 0x00007f9298011090 ***
zsh: abort (core dumped)  ~/Projects/pdfpc/build/bin/pdfpc lezione-04.pdf
`````

I tried to debug `pdfpc` using `gdb`, and I see something that goes along what you are saying: the backtrace shows a long list of functions in GStreamer libraries, but no reference to functions in the `pdfpc` codebase, so it might well be a problem with GStreamer itself.

Two more interesting details:

1. I get crashes even if I use the `pdfpc` bundled with Xubuntu 15.10, but it crashes less often. Only slides 16 and 18 cause problems (slide 8 runs fine), but in this case the crash happens only when I start the movie, not when the slide is displayed on the screen.

2. Interestingly enough, if I run `pdfpc` using Valgrind, no crash occurs. Unfortunately, the program runs so slowly that it is virtually impossible to do anything with it.

3. Playing the videos using the Parole Media Player bundled with Xubuntu 15.10 works smoothly. The interesting point here is that Parole is based on Gstreamer as well.

**Comment by rschroll** [comment] 2015-11-03 21:39
I can play all of the movies without problem on my system (Ubuntu 
14.04).  If you can post a traceback, I'll take a look at it.  But my 
guess from the information we have so far is that there is something 
going wrong inside of GStreamer itself.

**Comment by ziotom78** [comment] 2015-11-04 16:19
I have done a lot of tests in the last few days, it seems that the problem is indeed in GStreamer:

- I installed Xubuntu 15.10 in a virtual machine. This is the same distribution as the one I was using before, but this time I installed it from scratch, instead of updating an old 15.04 distro. In this case, only slide 16 causes problems (only audio, no video). Note that I had to patch `pdfpc` in order to avoid `xvimagesink`, asVirtualBox machines apparently do not support XV out of the box, I had to use `autovideosink`. (the Parole media player worked without problems.) `pdfpc` produced a number of warnings, but unfortunately I did not keep track of them, and I deleted the Virtual Machine, so it's not easy for me to recover them (details below).

- I installed Linux Mint 17.2 on a USB stick and installed `pdfpc` from the GitHub repository. In this case, every video played, but a lot of warnings about wrong usages of `free()` and `NULL` were printed on `stderr`. However, the program did not crash and the movies were played correctly. (Note that AFAIK Linux Mint 17.2 is based on the same set of packages present in Ubuntu 15.04, so they're a bit older than Xubuntu 15.10.)

- Based on the results in the previous point, I decided to back up my data and install a fresh copy of Linux Mint 17.2 on my laptop (sic!  Unfortunately I left the Xubuntu virtual machine out of the backup, so I lost the ability to recover the warnings I mentioned above in the first point). I have completed the process and with this configuration, `pdfpc` works like a charm with all the videos in the presentation. Strangely, the warning messages I saw when running Mint on a USB stick are disappeared, so I cannot report them here.

From my point of view, this issue can be closed. However, in all the tests I made I noticed that `pdfpc` seems more fragile than the Parole media player in its interface with GStreamer. If you want, it's ok for me if you keep this issue open in order to track this.

**Comment by rschroll** [comment] 2015-11-04 18:22
On Wed, Nov 4, 2015 at 11:19 AM, Maurizio Tomasi 
<notifications@github.com> wrote:
> However, in all the tests I made I noticed that pdfpc seems more 
> fragile than the Parole media player in its interface with GStreamer.

Out of curiosity, when you tested with Parole, did you play multiple 
movies in the same instance, or did you start a new instance for each 
movie?  If it was the latter, you may not have exercised the GStreamer 
destructors, which is where I would expect errors about free() to occur.

That said, I'm perfectly willing to believe that we're doing GStreamer 
stuff suboptimally.

**Comment by ziotom78** [comment] 2015-11-05 09:34
If I remember correctly, I started each movie separately when using Parole. But note that `pdfpc` crashed *before* the movie started playing: the exception happened when `pdfpc` tried to display the slide with the video on the screen. (If I understand `pdfpc`'s code correctly, this happened when the program created a GStreamer surface on the screen, attached the movie to it and set it to a paused state.) It is not clear to me why GStreamer was trying to free memory while doing such actions.

I quickly searched on the web for Parole's source code, but I was not able to find its repository (not that I have searched carefully). Probably it is part of the XFCE code base, if I have time in the next days I'll try again to find it. It might be an interesting read.

**Comment by rschroll** [comment] 2015-11-05 20:55
On Thu, Nov 5, 2015 at 4:34 AM, Maurizio Tomasi 
<notifications@github.com> wrote:
> But note that pdfpc crashed before the movie started playing: the 
> exception happened when pdfpc tried to display the slide with the 
> video on the screen.

Well, so much for that idea.

Parole's source code is here: http://git.xfce.org/apps/parole.  A quick 
glance through suggests that they're using Clutter to display the 
videos.  Frankly, it might make more sense for use to be using Clutter 
for the whole interface, but I don't think any of us are interested in 
rewriting that much code.

**Comment by sedimentorc** [comment] 2016-01-11 15:40
I also installed Xubuntu 15.10 in a virtual machine and would like to patch pdfpc as you did, ziotom78.

I just tried changing xvimagesink -> autovideosink in line 285 of movie.vala in src/classes/action and recompiling. There are no compilation errors, but I only get audio to play, no video. Would you please tell me if you made any other changes to get pdfpc to work in a virtual machine?

Thanks!

**Comment by ziotom78** [comment] 2016-01-12 09:42
Hi @sedimentorc, unfortunately I did not keep my VirtualBox machine and therefore cannot check which changes I had to implement. I just remember it was quite easy to do, so probably the substitution you made is the only one I did.

**Comment by AndreasBilke** [comment] 2017-08-11 08:14
If the problem arises again, please re-open!

**Closed by AndreasBilke** 2017-08-11 08:14 UTC
Labels: low priority

**Comment by MTangermann** [comment] 2020-01-15 12:40
Maybe I can help out with the error messages regarding GSTREAMER upon a crash during the video. 
(Using  pdfpc v4.0.2 wit Ubuntu 16.04, 4.4.0-170-generic).
---- snip ----
(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element inputselector3, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element inputselector2, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element identity, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element aconv, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element aqueue, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element abin, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element deinterlace, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element vdconv, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element vdbin, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element audiotee, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element streamsynchronizer1, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element playsink, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element playbin, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element identity, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element vconv, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element vqueue, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element vbin, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element playbin, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(pdfpc:2042): GStreamer-CRITICAL **: 
Trying to dispose element inputselector0, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.

---snap---
