### ISSUE TITLE
Terminal input

### ISSUE THREAD

**Issue by LecrisUT** [pdfpc/pdfpc#501] opened 2020-03-10 06:06 UTC
**Only submit a feature request if you read the SUPPORT.md file**

The feature wish description:
Correct me if I'm wrong, but currently pdfpc does not do anything with the inputs of the terminal window right? Could it be hooked up to take some basic commands?

Example use-case: automating tests for `homebrew`
```
pdfpc pdfpc-demo.pdf
(send quit command)
(check if return 0)
```

I have tried to automate it with other basic commands available for Mac with no success so far. Closest I got was using `osascript` to send the keystroke `Ctrl+q`. Unfortunately there are permission errors to use it in other scripts. `expect` would be the best alternative, but `pdfpc` does not recognize any of the input there.

**Comment by fnevgeny** [comment] 2020-03-10 11:07
Please have a look at the "Desktop integration" section of the manpage. Looks like it should work with macos  <https://formulae.brew.sh/formula/dbus>.

**Comment by LecrisUT** [comment] 2020-03-11 00:47
I don't think it's working.
```
Could not acquire DBus bus.

brew services
Name    Status  User   Plist
dbus    started *** /Users/***/Library/LaunchAgents/org.freedesktop.dbus-session.plist
```

I tried the example and it doesn't move the slide.

**Comment by fnevgeny** [comment] 2020-03-11 09:16
> Could not acquire DBus bus.

Likely, it's not related to pdfpc. Is dbus-daemon running? You can try any kind of a simple "Hello world" dbus exercise. <https://github.com/zbentley/dbus-osx-examples/tree/master/installation>

**Comment by LecrisUT** [comment] 2020-03-11 09:36
@fnevgeny It seems to work fine on my end:
Terminal1:
```
***@***: dbus-test-tool echo --session --name=com.$USER.echo
```
Terminal2:
```
***@***: dbus-send --session --print-reply --dest=com.$USER.echo /my/test/object my.test.service.TestInterface.TestMethod string:'testdata3'
method return time=1583919210.751491 sender=:1.6 -> destination=:1.7 serial=3 reply_serial=2
```

**Comment by fnevgeny** [comment] 2020-03-11 22:14
If this example <https://wiki.gnome.org/Projects/Vala/DBusServerSample> doesn't work, submit a Vala bug report please....

**Comment by LecrisUT** [comment] 2020-03-13 01:42
I have posted a bug report to the vala team [GNOME/vala#932](https://gitlab.gnome.org/GNOME/vala/issues/932). Hopefully they will find something soon.
Regarding `DBus` what is the use-case for it? Communication with external devices?
If it's not a crucial component, IMO it should not be used for writing the automated tests for the `homebrew` formula. Although I can't see a workaround to automatically close `pdfpc` after it (fails to) displays the presentation screens.

**Comment by fnevgeny** [comment] 2020-03-13 13:06
> I have posted a bug report to the vala team [GNOME/vala#932](https://gitlab.gnome.org/GNOME/vala/issues/932). Hopefully they will find something soon.

Good.

> Regarding `DBus` what is the use-case for it? Communication with external devices?

Communications between different desktop applications and services. Like pdfpc uses it to disable screensaver during the presentation.

> If it's not a crucial component

It works nicely under Linux. If it doesn't under a specific OS, the problem is the luck of interest/involvement from the users&developers of that platform...

Unfortunately, there is no similar truly universal, cross-platform mechanism. And it wouldn't be smart to invent something new; better to fix the existing one...

**Comment by fnevgeny** [comment] 2020-03-14 12:59
The macos/dbus issue is being handled upstream, closing the ticket here.

**Closed by fnevgeny** 2020-03-14 12:59 UTC
