### ISSUE TITLE
Scroll notes

### ISSUE THREAD

**Issue by bermeitinger-b** [pdfpc/pdfpc#350] opened 2018-06-12 09:37 UTC
**Only submit a feature request if you read the SUPPORT.md file**

The feature wish description:
I do have a small (?) feature request. On some of my slides, I have quite extensive notes that do not fit the screen. I could decrease the font size but at a certain point, it will become unreadable.
Is there a way to add a scroll bar or a scrolling function to the notes view?

Unfortunately, I'm not familiar with Vala and can't help implementing such feature. According to the SUPPORT document, this is unwanted but it may be a small thing to add. If not, and you don't want to spend time on it, feel free to close this issue.

**Comment by AndreasBilke** [comment] 2018-06-12 10:01
It already should have a scroll bar

**Comment by bermeitinger-b** [comment] 2018-06-12 12:10
Okay, so then I'll transform this to a bug report.

**Comment by AndreasBilke** [comment] 2018-06-12 12:13
Could you give some more information about your setup

**Comment by bermeitinger-b** [comment] 2018-06-12 12:36
**Expected Behaviour**
Show a scroll bar when to notes are too long or another mean of scrolling the notes.

**Actual Behaviour**
No scrollbar is shown if the notes are too long.

**Steps to reproduce**

1. Run pdfpdf with a pdf with notes that are too long for the display.
2. Notes are cut because there is no way to scroll

pdfpc version: pdfpc v4.1.2
Used Distribution (GTK version, vala version): Fedora 28
GTK: 
gtk2-2.24.32-2.fc28.x86_64
gtk2-2.24.32-2.fc28.i686
gtk3-3.22.30-1.fc28.x86_64
Vala:
vala-0.40.6-1.fc28.x86_64

Display Server (X/Wayland): X
HiDPI Setting (yes/no): no


I did a little more digging and the scoll bar is actually there when when moving the mouse cursor over it. But still, how can scroll? The mousewheel scrolls through the slides, as do the arrow keys and the mouse key.

**Comment by AndreasBilke** [comment] 2018-06-12 17:19
Actually, I can't reproduce this.

If my mouse is over the notes field, the scrolling happens there. If my
mouse is somewhere else, it scrolls the slides.

**Comment by bermeitinger-b** [comment] 2018-06-14 08:44
Thank you, I checked a little more and found that it is necessary (at least more convenient) to put `option disable-scrolling true` to put to the `pdfpcrc`.

Without this option, the slides are scrolling when 1) there is no scrollbar (text is not long enough) and 2) when scrolling inside the text but the text is already at the bottom or at the top.

**Comment by AndreasBilke** [comment] 2018-06-14 08:55
So we can close the issue?

**Closed** 2018-06-17 14:12 UTC
Labels: bug
