### ISSUE TITLE
Man page says there might be a small memory leak

### ISSUE THREAD

**Issue by andybarry** [pdfpc/pdfpc#124] opened 2016-01-30 22:05 UTC
Is this true?  I'm adding an issue so we can either keep track of it or remove that text.

```
BUGS
       There may be a small memory leak in the program. I am trying to  solve  it.
       It should not be too important for up to some hundreds of slides.
```

**Comment by AndreasBilke** [comment] 2017-02-06 19:47
I would like to keep this issue but remove the text from the man page. Since we are not tracking any issues in the man page I think it makes no sense in mentioning this (unconfirmed) bug there.

**Comment by AndreasBilke** [comment] 2017-09-18 08:34
As this MAY be a problem (but no one knows) I close this. If we really encounter memory leaks, we can open a new one.

**Closed by AndreasBilke** 2017-09-18 08:34 UTC
