### ISSUE TITLE
Presenter Window wrong Allignment and Size

### ISSUE THREAD

**Issue by Lygonius** [pdfpc/pdfpc#190] opened 2016-12-11 01:13 UTC
Hey there, first i want to thank you for the great work and keeping the project active. Second I have a request/ bug(?) I have compiled the code form github and using Fedora 25. When I start the presentation I can't see the timer due to wrong window size (see images attached). In addition the Presenterwindow is not aligned properly at the screen top side.
Thanks in advance
![bildschirmfoto von 2016-12-11 01-58-54](https://cloud.githubusercontent.com/assets/24500584/21077275/02d77080-bf47-11e6-8436-bea756b54b81.png)
Screenshot of "Fullscreen"
![bildschirmfoto von 2016-12-11 01-58-55](https://cloud.githubusercontent.com/assets/24500584/21077276/02d949be-bf47-11e6-931d-e06743f68b07.png)
In the Overview one can see the timer. I assume its "just" off screen

**Comment by AndreasBilke** [comment] 2017-01-01 18:40
I think this is a duplicate of #178

**Closed by AndreasBilke** 2017-01-01 18:40 UTC
Labels: help wanted
