### ISSUE TITLE
No video controls in the presenter view

### ISSUE THREAD

**Issue by zakjeens** [pdfpc/pdfpc#578] opened 2021-01-21 07:12 UTC
**Expected Behaviour**
To be able to use progressbar of video in the presenter view and to be able to set start&stop time for a video as in original video example
**Actual Behaviour**
No progressbar, video always starts at t=0s and loops, does not respect the start&stop time
**Steps to reproduce**

1. The zip with my video, the pdf and the tex file is here: https://we.tl/t-XpAIkFtlQ8
2. pdfpc video-example.pdf

pdfpc version: v4.5
Used Distribution (GTK version, vala version): Ubuntu 18.04, gtk version 3.22.30-1ubuntu4, Vala 0.40.23
Display Server (X/Wayland): Xorg
HiDPI Setting (yes/no): no

For info, the video supplied in the original example does show up with the progressbar and does start&stop at the desired time. I have however been unable to make any of my videos work the same way, tried with AVI (in the zip), with MP4 and MKV version of same video (originally mp4). I have had luck with one MKV, but none of my tested MP4 videos have progressbars.

**Comment by fnevgeny** [comment] 2021-01-21 13:23
I don't know what is "pdfpc-commands". Have you looked at the video example *we* provide? <https://github.com/pdfpc/pdfpc/releases/latest/download/pdfpc-video-example.zip>

Having said that, everything works fine for me. The progressbar becomes visible when you move the pointer to the bottom of the video.

**Comment by zakjeens** [comment] 2021-01-21 14:11
I downloaded the example from the link (sorry, I was under the impression that I was using the correct example) and inserted my video and still the problem remains. As you can see in the short video in the first two examples there is no progressbar no matter how long I try to point at the bottom of the video. And in the last example it shows at least 30s of the video and not between t=5s and t=12s. Once again, tried with mp4, mkv and avi versions of the same video.

https://user-images.githubusercontent.com/26329990/105361902-7eaab380-5bfa-11eb-9917-9dbaef05df3d.mp4

**Comment by fnevgeny** [comment] 2021-01-21 14:52
Are there any warnings/errors on stderr? BTW, I suppose you compiled pdfpc yourself, right?

**Comment by zakjeens** [comment] 2021-01-21 15:11
At launch time I get:

```
(pdfpc:7558): librsvg-WARNING **: 16:02:04.580: unknown line cap style null
(pdfpc:7558): librsvg-WARNING **: 16:02:04.581: unknown line join style null
(pdfpc:7558): librsvg-WARNING **: 16:02:04.590: unknown line cap style null
(pdfpc:7558): librsvg-WARNING **: 16:02:04.590: unknown line join style null
Screensaver inhibited
```
But that is also true for the original example with the apollo17 video, which works fine. No extra errors or warnings show up on the video slides.

And yes, I compiled it myself from pdfpc-4.5.0.tar.gz that I downloaded on January 12

**Comment by fnevgeny** [comment] 2021-01-21 15:20
1. Which window manager do you use?
2. Try running in the windowed mode (`-w both`). Any difference?
3. Is the control/progress bar usable with the original video file?

**Comment by zakjeens** [comment] 2021-01-21 16:11
1. gdm3 (Gnome display manager)
2. No changes with -w both
3. Original videos work fine, progress bar is visible and time controls also work.

Two precisions on the problem encountered:
1. I can actually change the progress of the video by clicking on the bottom of the video. It looks like the progress bar is simply invisible. See the video below
2. The start time in 3rd example IS in fact taken into account, but not the stop time. I can make the video start at t=15s, but it goes over stop time until the end of video and restarts at t=15s.

https://user-images.githubusercontent.com/26329990/105375928-7c9c2100-5c09-11eb-9631-ae43445b4b5e.mp4

**Comment by zakjeens** [comment] 2021-01-21 16:53
I thought I remembered being able to see the progress bar on my videos so I tried again with the version of pdfpc you can get through `apt-get install pdf-presenter-console` and it works!
In fact up to version 4.2.1 the video controls work exactly as expected but from 4.3.0 I start getting the problems I described above.

**Comment by fnevgeny** [comment] 2021-01-21 17:06
Try converting the movie to a format understood by one of `gstreamer1.0-plugins-good`. (You know, people do not call something "bad" for no reason; and `gstreamer1.0-plugins-bad` is needed for the playback of your video.) 

But again, I cannot reproduce you problem (even installed Ubuntu-18.04 to be on the safe side).

What is your video card/driver, BTW? Is everything `apt-get update`'d?

**Comment by fnevgeny** [comment] 2021-01-21 17:41
BTW, to get rid of the librsvg warnings, delete all lines with "null" like `stroke-opacity="null"` from `icons/spotlight.svg`.

**Comment by zakjeens** [comment] 2021-01-21 17:59
How can you see that 'gstreamer1.0-plugins-bad' is needed for playback of my video? I've never had any issues with their playback up till now to be honest (and they do work in pdfpc, just "over" the progress bar)

I ran the updater just to be safe, but after reboot it's still as before, v4.2.1 works well, but anything above v4.3.0 doesn't display the progress bar above the video.

**Comment by fnevgeny** [comment] 2021-01-21 18:15
> How can you see that 'gstreamer1.0-plugins-bad' is needed for playback of my video?

`apt-get remove gstreamer1.0-plugins-bad` and try to play the video back with `gst-play-1.0`.

You didn't reply re: video card/driver.

**Comment by zakjeens** [comment] 2021-01-22 11:00
I downloaded random youtube videos to test if it's just my stuff, but no - none of them work. I also compiled all possible outputs from Adobe Premiere Pro (that's where my original videos come from) and still no luck, so it can't be that. Especially since the v4.2.1. works perfectly and since you say that you cannot reproduce the problem when using the video I supplied.

Sorry about that, I missed that part of the question. Graphics: Intel® HD Graphics 530 (SKL GT2) and I'm using the open source X.Org X Server Nouveau display driver. Tried choosing the nvidia-driver-460, but nothing changed.

Honestly, since v4.2.1 works and you cannot reproduce the problem - this might be unsolvable. I have just one problem with v4.2.1 - the key bindings don't work (or don't exist yet), but I'd like the pointer to be of different size & color. Could you tell me what needs to be changed in the source to make the default pointer bigger and bright red?

**Comment by fnevgeny** [comment] 2021-01-22 11:58
> I downloaded random youtube videos to test if it's just my stuff, but no - none of them work. I also compiled all possible outputs from Adobe Premiere Pro (that's where my original videos come from) and still no luck, so it can't be that.

Well, let's first make sure you can play the video with `gstreamer1.0-plugins-bad` *uninstalled*. I have no desire to debug potential bugs in third-party software that even its authors consider non-production quality.

> Sorry about that, I missed that part of the question. Graphics: Intel® HD Graphics 530 (SKL GT2) and I'm using the open source X.Org X Server Nouveau display driver. Tried choosing the nvidia-driver-460, but nothing changed.

What?? Neither Nouveau or Nvidia drivers are needed for the Intel graphics chipset; how do you know either of them is used?

I strongly suggest running Ubuntu-20.04 live off a USB stick and test everything in the clean environment.

> Could you tell me what needs to be changed in the source to make the default pointer bigger and bright red?

Sorry, no time for that. We officially support only the latest released version. Everything is open source, so you can find relevant changes in the git logs.

**Comment by zakjeens** [comment] 2021-02-06 16:33
Sorry for the delay.
I made two persistent live usb sticks - one with Ubuntu 18.04 and the other with Ubuntu 20.04.
Indeed, once all the packages are installed on Ubuntu 20.04 pdfpc v4.5 works as expected. 
However, even on a clean Ubuntu 18.04 I still have exactly the same problems that I wrote about above.

**Comment by fnevgeny** [comment] 2021-02-06 20:48
Thanks for the update. Still, it sounds to me the issue is a problematic video driver for your chipset in 18.04. Are there some reservations that stop you from upgrading to 20.04?

**Comment by zakjeens** [comment] 2021-02-08 11:22
Yes, I have an ongoing project that will soon end and I cannot change the setup right before the deadline ;)

Anyway I finally found a converter that can make mkv videos from my mp4 videos that do have the controls in pdfpc v4.5! After a lot of dead ends it was IFME that did it for me.

However, now that everything works I see that there is a significant lag in v4.5 before displaying slides with images or videos. Like it takes several seconds before the slide changes. In v4.2.1 there's a rather long prerendering process for my 100+ slides, but then switching is smooth and fast.

**Comment by fnevgeny** [comment] 2021-02-08 17:35
> However, now that everything works I see that there is a significant lag in v4.5 before displaying slides with images or videos. Like it takes several seconds before the slide changes.

This shouldn't be the case unless you fast-forward (every couple of second or so) slides.

> In v4.2.1 there's a rather long prerendering process for my 100+ slides, but then switching is smooth and fast.

There are quite a few fine-tuning knobs for caching and pre-rendering. `man pdfpcrc`. You can alter the defaults to behave like in the old days, if that's what you really want.

As the original issue is resolved, I'm closing the ticket.

**Closed** 2021-02-08 17:40 UTC
Labels: cannot reproduce
