### ISSUE TITLE
Cannot play video on OSX

### ISSUE THREAD

**Issue by Pfeifenjoy** [pdfpc/pdfpc#423] opened 2019-02-01 12:04 UTC
**Expected Behaviour**
The video should start.

**Actual Behaviour**
I only see the image.

I get an error message in the command line:
```
Error creating video sink: Could not make element sink0 of type gtksink.
Gstreamer installation may be incomplete.
```

**Steps to reproduce**
1. I have installed pdfpc manually. -> Download, compile install
2. Start the demo of the video.

pdfpc version: 4.3.0
I have used homebrew to install all dependencies.
The main issue here is probably the gstreamer.
I have installed it as follows:
```
brew install gstreamer
brew install gst-plugins-good
```

**Comment by fnevgeny** [comment] 2019-02-01 13:02
Among the core developers, nobody uses/owns OSX. We thus rely on users submitting bugs to help in debugging, which is not always the case. Please review discussions in #331, #386.

**Comment by AndreasBilke** [comment] 2019-03-03 07:57
Please find the gstreamer dependency in brew which includes the gtk sink. If pdfpc still does not play the video you can reopen the issue.

**Comment by LecrisUT** [comment] 2019-06-04 09:42
If I may reopen this issue, after getting gstreamer with gtksink to work, I am still unable to play video on pdfpc.

gst-play-1.0 --videosink gtksink apollo17.avi

This works perfectly with gtk+ cairo renderer, but when I open the pdf file, the video won't show. I've added gstreamer and gst-plugins-good dependencies to the brew formula to get pdfpc to check for these modules and it finds them well.

Where can the error be?

**Comment by fnevgeny** [comment] 2019-06-04 22:45
Thanks for providing the info,

> `gst-play-1.0 --videosink gtksink apollo17.avi`
> 
> This works perfectly with gtk+ cairo renderer,

Does the window look like the native one or X11?

> `gst-launch-1.0 filesrc location=apollo17.avi ! decodebin ! gtksink`
> and I get the following error:

I get it too, so it must be normal :)

**Comment by LecrisUT** [comment] 2019-06-05 02:18
> Does the window look like the native one or X11?

I'm trying to confirm what window it is, but I am not certain. It is definitely not an XQuarts window.
The title of the window is just "gtk+ cairo renderer"
It might be an X11 window since it opens a different application in the dock, although the name is just "gst-play-1.0".

If i play with the default videosink, there is no new application opened. The renderer is OpenGL, and it is the same as "glimagesink". Also, OpenGL uses the cocoa display right now.

I will recompile the base gst plugins to get the x11 videosinks and see if those are similar.

**Comment by fnevgeny** [comment] 2019-06-08 15:39
> `gst-play-1.0 --videosink gtksink apollo17.avi`
> 
> This works perfectly with gtk+ cairo renderer,

OK, I bit the bullet and installed macOS under VBox... So now please list all steps a newbie needs to repeat to get to this point. So far, I'm getting

`Couldn't create specified video sink 'gtksink'`

**Comment by fnevgeny** [comment] 2019-06-09 15:31
Well, I don't know what's wrong with the homebrew build of gst-plugins-good, but installing it manually works fine, with gtksink included. Then the only required change is a trivial fix that is now in the [4.3-maintenance branch](https://github.com/pdfpc/pdfpc/tree/4.3-maintenance). With that, movies play back fine. AFAICT everything is native macOS windows. Please confirm.

**Comment by fnevgeny** [comment] 2019-06-09 20:12
Fine, you need to
`brew edit gst-plugins-good`
and add `depends_on "gtk+3"`. After that,
`brew install -s gst-plugins-good`
and proceed with the normal pdfpc compilation.

**Comment by LecrisUT** [comment] 2019-06-10 00:14
@fnevgeny  Sorry for not getting back to yo earlier, glad you got it working. Yes it is working on this end also.

I will do some messing around, and confirm the minimum edit required.
Probably we cannot have all of the edits within the `pdfpc homebrew`.

Thanks again for the changes.

**Comment by fnevgeny** [comment] 2019-06-11 09:15
Good. Can you please take care of contacting relevant homebrew devs?

**Comment by AndreasBilke** [comment] 2019-06-11 09:27
Thank you @fnevgeny for finding this out.

@LecrisUT I close this issue again, since the problem is at the homebrew side.

**Closed by AndreasBilke** 2019-06-11 09:27 UTC
Labels: needs-feedback

**Comment by LecrisUT** [comment] 2019-06-12 02:27
@fnevgeny I'm learning how to edit the homebrew formulas and I think I'm getting the hang of it. If we can increment the version with the current fix, I will update the pdfpc formula as well

**Comment by fnevgeny** [comment] 2019-06-12 06:36
@LecrisUT Sure, we'll prepare 4.3.3 soon. Please propose the necessary changes to pdfpc README and FAQ to be included in the new release.

**Comment by LecrisUT** [comment] 2019-06-14 00:46
Ok, so `gtk+3` support is officially back in `homebrew gstreamer`.
I haven't managed to come up with anything to include in the Readme or FAQ.

For the macOS, just add that homebrew version includes video support, and I'll update pdfpc formula as soon as the new release is up.

**Comment by fnevgeny** [comment] 2019-06-18 22:24
@LecrisUT 4.3.3 is [there](https://github.com/pdfpc/pdfpc/releases/tag/v4.3.3).

**Comment by LecrisUT** [comment] 2019-06-19 00:07
Something is off. The new version does not register any keyboard commands, at least on MacOS.

**Comment by fnevgeny** [comment] 2019-06-19 14:16
Argh. My bad. I think I stepped on that rake once before. https://github.com/pdfpc/pdfpc/commit/6a5b1b630b2c88c303560133e00d07cd43aa79bc

**Comment by AndreasBilke** [comment] 2019-06-20 11:09
@LecrisUT I pushed a new release (v4.3.4). Does everything work for you now?

**Comment by LecrisUT** [comment] 2019-06-21 00:38
@AndreasBilke, everything works perfectly, thank you, @fnevgeny also.
I've submitted a PR on `homebrew`, it should be updated within 24 hours.

If there are any tests you need for macOS in the future let me know.
