### ISSUE TITLE
Content and cursor of notes view invisible

### ISSUE THREAD

**Issue by thvitt** [pdfpc/pdfpc#511] opened 2020-04-02 15:24 UTC
**Expected Behaviour**

In the presenter console, I would expect to see the notes and the cursor to appear when pressing Ctrl+n.

**Actual Behaviour**

The notes view is just a white rectangle, neither notes nor cursor can be seen. Some behaviour seems to be there, though: When blindly typing text, it is saved as note to the .pdfpc file.

After typing some text, it is possible to select and copy the text using the context menu. This doesn’t change anything wrt the notes screen, neither selection nor text appear somewhere.

**Steps to reproduce**

1. open a presentation, e.g. the demo presentation
2. press ctrl+n
3. blindly type some text
4. esc, close pdfpc

pdfpc version: both v4.3.4 and current master show the behaviour
Used Distribution (GTK version, vala version): Debian bullseye/sid, GTK 3.24.14-1, Vala 0.48.2
Display Server (X/Wayland): X
HiDPI Setting (yes/no): yes

I have removed my ~/.config/pdfpc directory prior to testing.

**Comment by fnevgeny** [comment] 2020-04-02 15:31
Does the area become white only when you edit the notes?

**Comment by thvitt** [comment] 2020-04-02 15:34
no, it is always white and doesn't change a bit whatever I do.

**Comment by fnevgeny** [comment] 2020-04-02 15:42
Please upload screenshot of the whole presenter window.

**Comment by thvitt** [comment] 2020-04-02 16:01
![2020-04-02_17-59](https://user-images.githubusercontent.com/1906208/78271005-eb3db000-750b-11ea-8f6d-b6b68403b650.png)

**Comment by fnevgeny** [comment] 2020-04-02 16:13
Try setting some fancy colors in ~/.config/pdfpc/pdfpc.css, e.g.
```
textview * {
    background-color: red;
    color: blue;
}
```

**Comment by thvitt** [comment] 2020-04-02 16:31
Hmm, doesn’t help, although the stylesheet is read in principle:

```css
window {
    background: green;
    color: purple;
}
textview * {
    background-color: red;
    color: blue;
}
```
yields this screenshot:
![Screenshot from 2020-04-02 18-27-18](https://user-images.githubusercontent.com/1906208/78274218-26da7900-7510-11ea-975b-c6b06d333f28.png)

**Comment by fnevgeny** [comment] 2020-04-02 16:40
Yes, something overrides it. Probably from the Gtk theme? You can copy the entire system `pdfpc.css` and play with anything there...

**Comment by fnevgeny** [comment] 2020-04-02 16:42
Also, try running as another (new?) user.

**Comment by thvitt** [comment] 2020-04-02 17:39
ah, for Mr. Testuser everything is OK. I didn’t know the view is intended to be white on black :-)

I wasn’t able yet to find the culprit on my account, though. The problem remains even after renaming my whole .config .local .gnome and .themes folders, and appearently no other css file is read successfully
```
% grep css pdfpc.strace | grep -v ENOENT                          
access("/usr/share/themes/Default/gtk-3.0/gtk-keys.css", F_OK) = 0
openat(AT_FDCWD, "/usr/share/themes/Default/gtk-3.0/gtk-keys.css", O_RDONLY) = 10
stat("/usr/local/share/pixmaps/pdfpc/pdfpc.css", {st_mode=S_IFREG|0644, st_size=1019, ...}) = 0
openat(AT_FDCWD, "/usr/local/share/pixmaps/pdfpc/pdfpc.css", O_RDONLY) = 11
```
I'm giving up for now, thanks for your help

**Comment by fnevgeny** [comment] 2020-04-02 18:02
> The problem remains even after renaming my whole .config .local .gnome and .themes folders,

And logging off/on after that?

**Comment by fnevgeny** [comment] 2020-05-09 16:34
Closing the issue until a reproducible case can be found.

**Closed** 2020-05-09 16:34 UTC
Labels: needs-feedback

**Comment by mwshinn** [comment] 2020-06-05 13:36
I just wanted to add that I am having the same issue.  However, I noticed that this issue is a regression: it does not occur in pdfpc-4.1.2, but it does occur in pdfpc-4.2.  Looking at intermediate commits, it can be narrowed down to 5f33efd, i.e. it does not occur in 7c80163, but it does occur in 5f33efd.

Happy to do any other tests that may help diagnose the issue.  Thanks for taking a look!

My system details: 

uname -a: Linux compname 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

OS: Ubuntu 18.04.2 LTS running Openbox

Here is cmake output listing versions of different libraries:

```
-- The C compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Vala: /usr/bin/valac (found suitable version "0.40.17", minimum required is "0.26")
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'gobject-2.0'
--   Found gobject-2.0, version 2.56.4
-- Checking for module 'gio-2.0'
--   Found gio-2.0, version 2.56.4
-- Checking for module 'gee-0.8'
--   Found gee-0.8, version 0.20.1
-- Checking for module 'poppler-glib>=0.22'
--   Found poppler-glib, version 0.62.0
-- Checking for module 'gtk+-3.0>=3.10'
--   Found gtk+-3.0, version 3.22.30
-- GTK is compiled with X11 -- enabling X11 support
-- Checking for module 'x11'
--   Found x11, version 1.6.4
-- Checking for module 'gthread-2.0'
--   Found gthread-2.0, version 2.56.4
-- Checking for module 'pangocairo'
--   Found pangocairo, version 1.40.14
-- Checking for module 'gstreamer-1.0'
--   Found gstreamer-1.0, version 1.14.5
-- Checking for module 'gstreamer-base-1.0'
--   Found gstreamer-base-1.0, version 1.14.5
-- Checking for module 'gstreamer-audio-1.0'
--   Found gstreamer-audio-1.0, version 1.14.5
-- Checking for module 'gstreamer-video-1.0'
--   Found gstreamer-video-1.0, version 1.14.5
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/pdfpc-4.1.2/build
```

**Comment by mwshinn** [comment] 2020-06-05 15:24
Oops, sorry, I was confused by how github was organizing the commits.  The commit that broke it for me was: 25b791db973ee8ab215e99bc3530d682572fa56e (i.e. commit  726a3eeb73bdb7fc9df95d51953caee9b3103cfa was just fine).  This commit changes some CSS, but when I tried using the CSS from the older revision and the code from the newer one, it still did not work, so it appears to go beyond just the CSS.

**Comment by mwshinn** [comment] 2020-06-05 16:49
I figured out the solution to this problem, which is surprisingly not related to CSS: the problem only occurs for me when GTK_IM_MODULE is set to "xim".  When I change my input method to "ibus" or "uim", it works as expected.  Looks like this isn't an issue with pdfpc, but rather, some bug in the xim module.

Thanks for all your work on pdfpc - having such customizable presentation software makes giving talks so much easier!

**Comment by fnevgeny** [comment] 2020-06-05 18:44
Wow. So weird. Yes, I can confirm setting `GTK_IM_MODULE` to `xim` triggers the problem. How did you find??

**Comment by mwshinn** [comment] 2020-06-05 19:03
I had some problems in the TLA+ GUI (also GTK-based) when using xim a while back (https://github.com/tlaplus/tlaplus/issues/390) so it seems that xim just doesn't work all that well with GTK.

**Comment by thvitt** [comment] 2020-06-06 10:44
Ah, I can confirm that as well – switching to UIM for pdfpc makes the notes work and pdfpc even more useful :)

**Comment by fnevgeny** [comment] 2020-06-07 21:01
Yes, `xim` has a serious issue(s) with `gtk`... Not sure which one is to blame, though. Please see the linked PR; it does not really fix this, but at least makes the notes usable when the toolbox is not toggled on.

**Comment by fnevgeny** [comment] 2020-06-07 21:08
@AndreasBilke do you think we should programmatically check for `GTK_IM_MODULE=xim` and issue a warning?

**Comment by AndreasBilke** [comment] 2020-06-08 16:23
@fnevgeny Since we don't have workaround code just for `xim` but just a warning I would agree on checking that in code.

**Comment by fnevgeny** [comment] 2020-06-08 17:38
BTW, to see the funny way `xim` interacts with the GUI add
```
            this.toolbox_container.halign = Gtk.Align.START;
            this.toolbox_container.valign = Gtk.Align.START;
```
and drag the toolbox around the window...
